@Metadata.layer: #CORE

@UI:{ 
headerInfo:{ 
                 typeNamePlural: 'List Employee - Table Header',
                typeName: 'Employee Detail',
                title:{ value: 'Employee_Id'}
           }
}

annotate view  ZI_RAP_EMP_887
    with 
{

     // OBJECT PAGE 
   @UI.facet: [ 
                { 
                    id:              'Detail',
                    purpose:         #STANDARD,
                    type:            #IDENTIFICATION_REFERENCE,
                    label:           'Employee Detail',
                    position:        10 
                 } ,
                 { 
                    id:              'Department',
                    purpose:         #STANDARD,
                  
                    label:           'Department Detail',
                    position:        20 
                 } 
              ]               
    // ELEMENT LIST
  @UI: { 
  lineItem: [{ position: 10 } ],
  identification: [ { label: 'Employee ID',position: 10 } ],
  fieldGroup:     [ { label: 'Employee_Id',qualifier: 'Fieldgroup:HeaderItems', 
                            position: 10 } ,
                            { label: 'Employee_Id',qualifier: 'Fieldgroup1', 
                            position: 10 }] }
  Employee_Id;
  @UI: { 
  lineItem: [{ position: 20 } ],
  identification: [ {label: 'Employee Name', position: 20 } ],
  fieldGroup:     [ { label: 'Employee_Name',qualifier: 'Fieldgroup:HeaderItems', 
                            position: 20 } ] }
  Employee_Name;
  
 
  @UI: { 
  lineItem: [{ position: 30 } ],
  identification: [ { label: 'Employee Address', position: 30 } ],
  fieldGroup:     [ { label: 'Employee_Address',qualifier: 'Fieldgroup:HeaderItems', 
                            position: 30 } ] }
  Employee_Address;
    @UI: { 
    lineItem: [{ position: 40 } ],
    identification: [ { label: 'Department ID',position: 40 } ],
    fieldGroup:     [ { label: 'Deparment_Id',qualifier: 'Fieldgroup:HeaderItems', 
                            position: 40 } ] }
  Deparment_Id;
}
